name: Build Windows App

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install customtkinter pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --icon=icon.ico app.py

      - name: Install Inno Setup
        run: |
          choco install innosetup -y

      - name: Build Installer
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: app-exe
          path: dist/app.exe

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: output/setup.exe
